module:
    hugoVersion:
        extended: true
        min: "0.87.0"

params:
    mainSections:
        - post
    featuredImageField: image
    rssFullContent: true
    favicon:

    footer:
        since: 2024
        customText: A part of <b>VISION IT 67</b> project

    dateFormat:
        published: 02 Jan 2006
        lastUpdated: 02 Jan 2006 15:04 MST


    sidebar:
        compact: false
        emoji:
        subtitle: All your SAMO-related works
        avatar:
            enabled: false
            local: true
            src: img/avatar.png

    article:
        math: false
        toc: true
        readingTime: false
        license:
            enabled: false
            default: Licensed under CC BY-NC-SA 4.0

    comments:
        enabled: false
        provider: disqus

        disqusjs:
            shortname:
            apiUrl:
            apiKey:
            admin:
            adminLabel:

        utterances:
            repo:
            issueTerm: pathname
            label:

        beaudar:
            repo:
            issueTerm: pathname
            label:
            theme:        

        remark42:
            host:
            site:
            locale:

        vssue:
            platform:
            owner:
            repo:
            clientId:
            clientSecret:
            autoCreateIssue: false

        # Waline client configuration see: https://waline.js.org/en/reference/client/props.html
        waline:
            serverURL:
            lang:
            visitor:
            avatar:
            emoji:
                - https://cdn.jsdelivr.net/gh/walinejs/emojis/weibo
            requiredMeta:
                - nick
                - mail
            locale:
                admin: Admin
                placeholder:

        twikoo:
            envId:
            region:
            path:
            lang:

        giscus:
            repo:
            repoID:
            category:
            categoryID:
            mapping:
            strict:
            lightTheme:
            darkTheme:
            reactionsEnabled: 1
            emitMetadata: 0
            inputPosition:
            lang:

        gitalk:
            owner:
            admin:
            repo:
            clientID:
            clientSecret:

        cusdis:
            host:
            id:

    widgets:
        homepage: []
        page: []

    opengraph:
        twitter:
            # Your Twitter username
            site:

            # Available values: summary, summary_large_image
            card: summary_large_image

    defaultImage:
        opengraph:
            enabled: false
            local: false
            src:

    colorScheme:
        # Display toggle
        toggle: false

        # Available values: auto, light, dark
        default: light

    imageProcessing:
        cover:
            enabled: true
        content:
            enabled: true

# /// Menu items

# List menu that are EXTERNAL here only.
# If the entity is internal link, use frontmatter in that page

menu:
    social:
    - identifier: "ig"
      url: "/"
      params:
        icon: instagram

    main:
    - identifier: "booking-md"
      name: "ระบบจองห้องกลาง"
      url: "https://vichakarn-md.web.app/reserve"
      weight: -90
      params:
      newTab: true

    - identifier: "booking-mdi"
      name: "ระบบจองห้อง MDi"
      url: "https://vichakarn-md.web.app/reserve"
      weight: -89
      params:
      newTab: true

    - identifier: "document"
      name: "ยื่นขอเอกสาร"
      url: "/"
      weight: -70
      params:
      newTab: true

    - identifier: "broken"
      name: "แจ้งทรัพย์สินเสียหาย"
      url: "/"
      weight: -78
      params:
      newTab: true

    - identifier: "follow"
      name: "ติดตามโครงการและปัญหา"
      url: "/"
      weight: -75
      params:
      newTab: true

    - identifier: "guide"
      name: "Survival Guide"
      url: "/"
      weight: -50
      params:
      newTab: true
    
    - identifier: "project"
      name: "เขียนโครงการ"
      url: "/"
      weight: -100
      params:
      newTab: true
    
    - identifier: "mental"
      name: "Mental Support"
      url: "/"
      weight: 100
      params:
      newTab: true
    
    - identifier: "calendar"
      name: "ปฏิทินกิจกรรม"
      url: "/"
      weight: -100
      params:
      newTab: true

    - identifier: "mddatabase"
      name: "MD Database"
      url: "/"
      weight: -10
      params:
      newTab: true